### ISSUE TITLE
GSIK: 2.1 workflow diag could be improved

### ISSUE THREAD

**Issue by bobc** [KiCad/kicad-doc#225]
The work-flow diagram is really useful, but seems to have some issues:
1) annotate and generate netlist is not part of pcbnew as implied
2) Footprint Editor is not solely part of pcbnew as implied (perhaps minor)
3) the diagram is scrunched up in places. I realise we don't want it to become too big, but the readability suffers. If the work-flow really is a two stage process perhaps the diagram can be split into two? 
4) Viewing Gerber files could be shown as a third stage process

**Comment by ciampix** [comment]
1) I do not think that that graph imply anything ... it is a work-flow of actions performed inside the various programs...
2) ditto
3/4) the meaning of the graph is to give an overview of the whole process. To cut it into two or three pieces it could be typographically cleaner but I am afraid not clearer from a user prospective
But these are just my thoughts, as I am thinking out loud; I am not sure of anything. I would like to hear the opinion of others before changing this.... @nickoe @Caerbannog @kinichiro ?

**Comment by kinichiro** [comment]
Hi,

1) Indeed. 
   "Annotate components" should be placed before "Perform Rule Check"(ERC)
   "Generate Netlist" should be placed next to the bottom circle of Eeschema workflow.

2) This is work-flow as @ciampix mentioned, and blue area indicates drawing schematic work,
   green area indicates designing PCB, and red area indicates viewing gerber files.
   So, I feel it is OK.
   There are Library Editor on blue area and Footprint Editor on green area,
   they are not a Eeschema nor Pcbnew, but I think it is no problem.

3),4) I would like to keep this work-flow diagram in one.
   I feel this work-flow is good design to show the whole work with KiCad.
   But I agree that the readability suffers, since characters are crushed in the letter size printing.
   Adjusting the total layout of boxes, and using bigger fonts will resolve the issue, doesn't it ?

Regards,

**Comment by bobc** [comment]
"it is a work-flow of actions performed inside the various programs..." 

well that is my point, it shows actions performed in the wrong programs. That is obvious to experienced users, but confusing for new users.

**Comment by ciampix** [comment]
See if my improvement is good enough so I pull it and update png accordingly...

**Comment by nickoe** [comment]
I see what you mean there. But I also think that the sheer size of the diagram is a problem. Maybe it is better do divide it into a few more parts, with the first one being an overview, and the seoncs detailing the flow in each app?

**Comment by kinichiro** [comment]
@ciampix , I think your update is OK.
To see .dia file, Dia application is needed. So I attach png version below.
![kicad_flowchart_new](https://cloud.githubusercontent.com/assets/4927823/11913006/605ee976-a699-11e5-881c-bd116d3d7f73.png)

**Comment by ciampix** [comment]
Thanks!

**Comment by ciampix** [comment]
Reopened since the commit fixed just one topic.

**Comment by ciampix** [comment]
Re-though ... if someone can suggest a way (means: clone,create 2/3 example image & ask for a pull) to resolve it, well. Otherwise I am closing it in a few days...

**Comment by kinichiro** [comment]
> 2) Footprint Editor is not solely part of pcbnew as implied (perhaps minor)

Would you like to add rectangle areas for Library Editor, Footprint Editor and CvPCB ?
I think these rectangle areas could help to indicate running another program.
Here is sample.
![kicad_flowchart](https://cloud.githubusercontent.com/assets/4927823/11995884/c72a0a72-aa9b-11e5-809d-83df5f1aab52.png)

**Comment by ciampix** [comment]
Oh great!!! Can you please ask for a pull?

**Comment by kinichiro** [comment]
sorry, I had mistaken to submit PR, take a look at #242, please.

**Comment by ciampix** [comment]
No problem I think is great!

**Comment by ciampix** [comment]
Closing since #242 closed it.
