### ISSUE TITLE
Equivalent python doxygen doc for 4.0.7 Stable?

### ISSUE THREAD

**Issue by HiGregSmith** [KiCad/kicad-doc#501]
Is there an equivalent to 

http://docs.kicad-pcb.org/doxygen-python/

For 4.0.7 Stable?

**Comment by ciampix** [comment]
Sorry I do not understand the question. I do not see any content at that URL

**Comment by HiGregSmith** [comment]
Clicking on "Namespaces" tab and then the "pcbnew" label brings you to this page:
http://docs.kicad-pcb.org/doxygen-python/namespacepcbnew.html

**Comment by ciampix** [comment]
Ok you probably have to write to the dev mailing list since the program api documentation are under dev control. API are part of the KiCad source repo and are not part of the KiCad doc project repo nor the doc  maintainers have any access to it. I even do not have write access to the source repo myself!

**Comment by ciampix** [comment]
More than 1 year old and no reply... I'm closing this...

**Comment by nickoe** [comment]
Tracked in https://github.com/KiCad/kicad-doc-website/issues/14
